version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack,security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elasticsearch_network
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elasticsearch_network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.11.0
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elasticsearch_network
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config/logstash.yaml:/usr/share/logstash/config/logstash.yaml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro

networks:
  elasticsearch_network:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
